// staffer-react-mobx/src/app-bar/AppBar.jsx
import './app-bar.scss';
import React from 'react';
import {connect} from 'mobx-connect';
import {observer} from 'mobx-react';

@connect('store')
@observer
export default class AppBar extends React.Component {

    render() {
        let {store: {summary}} = this.context;
        let {open, closed, total} = summary;

        return (
            <div className={`toolbar ${this.props.className}`} color="primary">
                <h1 className="toolbar-title shrink">Staffer</h1>
                <span className="toolbar-gap"/>
                <span className="toolbar-open shrink">Open: {open}</span>
                <span className="toolbar-closed shrink">Closed: {closed}</span>
                <span className="toolbar-total shrink">Total: {total}</span>
            </div>
        );

    }

}

AppBar.defaultProps = {};

// staffer-ng2-ngrxstore/src/app/app-bar/app-bar.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import { MdToolbar } from "@angular2-material/toolbar/toolbar";
import { NeedsSummary } from "../shared/models/index";

@Component({
    moduleId: module.id,
    selector: 'app-bar',
    templateUrl: 'app-bar.component.html',
    styleUrls: [ 'app-bar.component.css' ],
    directives: [ MdToolbar ],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppBarComponent {

    @Input()
    summary:NeedsSummary;
}

<md-toolbar class="toolbar" color="primary">
    <h1 class="toolbar-title">Staffer</h1>
    <span class="toolbar-gap"></span>
    <span class="toolbar-open">Open: {{summary.open}}</span>
    <span class="toolbar-closed">Closed: {{summary.closed}}</span>
    <span class="toolbar-total">Total: {{summary.total}}</span>
</md-toolbar>
