// staffer-react-mobx/src/needs-panel/NeedsFilter.js
import './NeedsFilter.css';

import {connect} from 'mobx-connect';
import {observer} from 'mobx-react';

import Button from '../../components/Button';
import Input from '../../components/Input';
import Select from '../../components/Select';

@connect('store')
@observer
export default class NeedsFilter extends React.Component {

    constructor(props) {
        super(props);
        this.applyFilter = this.applyFilter.bind(this);
        this.notifyFilterChange = this.notifyFilterChange.bind(this);
    }


    render() {
        const {filter, entityMap: {projects, skills, statuses}} = this.context.store;

        return (
            <div className="NeedsFilter">
                <div className="NeedsFilter-inputContainer">
                    <Input label="From"
                           id="minStartDate"
                           placeholder="Start Date"
                           type="date"
                           defaultValue={filter.minStartDate}
                           handleAction={this.notifyFilterChange}
                           ariaLabel="From Date"/>
                </div>

                <div className="NeedsFilter-inputContainer">
                    <Input label="To"
                           id="maxStartDate"
                           placeholder="End Date"
                           type="date"
                           defaultValue={filter.maxStartDate}
                           handleAction={this.notifyFilterChange}
                           ariaLabel="To Date"/>
                </div>


                <div className="NeedsFilter-inputContainer">
                    <Select label="Project" id="projectId"
                            entryMap={projects}
                            handleAction={this.notifyFilterChange}/>
                </div>

                <div className="NeedsFilter-inputContainer">
                    <Select label="Skill" id="statusId"
                            entryMap={skills}
                            handleAction={this.notifyFilterChange}/>
                </div>

                <div className="NeedsFilter-inputContainer">
                    <Select label="Status" id="statusId"
                            entryMap={statuses}
                            handleAction={this.notifyFilterChange}/>
                </div>

                <Button handleAction={this.applyFilter} label="Search"
                        className="Button Button--default u-sizeFull"/>
            </div>
        );
    }

    notifyFilterChange(key, value) {
        const {store} = this.context;
        store.setFilterField(key, value);
    }

    applyFilter() {
        const {store} = this.context;
        store.loadNeeds();
    }
}

NeedsFilter.defaultProps = {};

// staffer-ng2-ngrxstore/src/app/needs-panel/needs-filter/needs-filter.component.ts
import {
    Component,
    EventEmitter,
    Input,
    Output,
    ChangeDetectionStrategy,
    ChangeDetectorRef
} from "@angular/core";
import { MdButton } from "@angular2-material/button";
import { MD_INPUT_DIRECTIVES } from "@angular2-material/input";
import { FilterState, Project, Skill, Status } from "../../shared/models/index";
import { Store } from "@ngrx/store";
import { AppState } from "../../shared/store/state";

@Component({
    moduleId: module.id,
    selector: 'app-needs-filter',
    templateUrl: 'needs-filter.component.html',
    styleUrls: [ 'needs-filter.component.css' ],
    directives: [ MdButton, MD_INPUT_DIRECTIVES ],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NeedsFilterComponent {

    filterState:FilterState = new FilterState();

    @Input()
    statuses:Status[] = [];

    @Input()
    projects:Project[];

    @Input()
    skills:Skill[];

    @Output()
    filterChange = new EventEmitter<FilterState>();

    constructor(private store:Store<AppState>,
                ref:ChangeDetectorRef) {

        store.select('filter')
            .subscribe((filter:FilterState)=> {
                this.filterState = filter;
                ref.markForCheck();
            });

    }

    notifyFilterChange() {
        this.filterChange.emit(this.filterState);
    }
}

<md-input type="date" [(ngModel)]="filterState.minStartDate" placeholder=""
          aria-label="From Date"></md-input>

<md-input type="date" [(ngModel)]="filterState.maxStartDate" placeholder=""
          aria-label="To Date"></md-input>

<div class="input-container">
    <label>Project</label>
    <select required
            [(ngModel)]="filterState.projectId">
        <option [value]="-1">All</option>
        <option *ngFor="let p of projects" [value]="p.id">{{p.name}}</option>
    </select>
</div>

<div class="input-container">
    <label>Skill</label>
    <select required
            [(ngModel)]="filterState.skillId">
        <option [value]="-1">All</option>
        <option *ngFor="let s of skills" [value]="s.id">{{s.name}}</option>
    </select>
</div>

<div class="input-container">
    <label>Status</label>
    <select required
            [(ngModel)]="filterState.status">
        <option *ngFor="let s of statuses" [value]="s.id">{{s.name}}</option>
    </select>
</div>

<button md-raised-button class="search-button" color="primary"
        (click)="notifyFilterChange()">Search
</button>
