// staffer-react-mobx/src/needs-panel/needs-filter/NeedsFilter.jsx
import {connect} from 'mobx-connect';
import {observer} from 'mobx-react';
import values from 'lodash/values';
import './needs-filter.scss';

@connect('store')
@observer
export default class NeedsFilter extends React.Component {

    render() {
        const {filter, entityMap: {projects, skills, statuses}} = this.context.store;

        return (
            <div>
                <input type="date"
                       defaultValue={filter.minStartDate}
                       placeholder="Start Date"
                       onChange={event=>this.notifyFilterChange('minStartDate', event.target.value)}
                       aria-label="From Date"/>

                <span> to </span>
                
                <input type="date"
                       defaultValue={filter.maxStartDate}
                       placeholder="End Date"
                       onChange={event=>this.notifyFilterChange('maxStartDate', event.target.value)}
                       aria-label="To Date"/>

                <div className="input-container">
                    <label>Project</label>
                    <select defaultValue={filter.projectId}
                            onChange={(event)=>this.notifyFilterChange('projectId', event.target.value)}>
                        <option value="-1">All</option>
                            {
                                values(projects)
                                    .map(p=> {
                                        return <option value={p.id} key={p.id}>{p.name}</option>
                                    })
                            }
                    </select>
                </div>

                <div className="input-container">
                    <label>Skill</label>
                    <select defaultValue={filter.skillId}
                            onChange={(event)=>this.notifyFilterChange('skillId', event.target.value)}>
                        <option value="-1">All</option>
                            {
                                values(skills)
                                    .map(x=> {
                                        return <option value={x.id} key={x.id}>{x.name}</option>
                                    })
                            }
                    </select>
                </div>

                <div className="input-container">
                    <label>Status</label>
                    <select defaultValue={filter.statusId}
                            onChange={(event)=>this.notifyFilterChange('statusId', event.target.value)}>
                            {
                                values(statuses)
                                    .map(x=> {
                                        return <option value={x.id} key={x.id}>{x.name}</option>
                                    })
                            }
                    </select>
                </div>

                <button className="search-button"
                        onClick={()=>this.applyFilter()}>Search
                </button>
            </div>
        );
    }

    notifyFilterChange(key, value) {
        const {store} = this.context;

        store.setFilterField(key, value);
    }

    applyFilter() {
        const {store} = this.context;
        store.loadNeeds();
    }
}

NeedsFilter.defaultProps = {};

// staffer-ng2-redux/src/app/needs-panel/needs-filter/needs-filter.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { MdButton } from '@angular2-material/button';
import { MD_INPUT_DIRECTIVES } from '@angular2-material/input';

import { FilterState, Project, Skill } from '../../shared/models/index'

@Component({
    moduleId: module.id,
    selector: 'app-needs-filter',
    templateUrl: 'needs-filter.component.html',
    styleUrls: ['needs-filter.component.css'],
    directives: [MdButton, MD_INPUT_DIRECTIVES]
})
export class NeedsFilterComponent implements OnInit {

    filterState: FilterState = new FilterState();

    statuses = [
        { id: 'all', name: 'All'},
        { id: 'open', name: 'Open'},
        { id: 'closed', name: 'Closed'}
    ];

    @Input() projects: Project[];
    @Input() skills: Skill[];
    @Output() filterChanged = new EventEmitter();

    constructor() {
    }

    ngOnInit() {
        this.handleFilterChanged();
    }

    handleFilterChanged() {
        this.filterChanged.emit(this.filterState);
    }
}

<md-input type="date" [(ngModel)]="filterState.minStartDate" placeholder="" aria-label="From Date"></md-input>

<md-input type="date" [(ngModel)]="filterState.maxStartDate" placeholder="" aria-label="To Date"></md-input>

<div class="input-container">
    <label>Project</label>
    <select required
            [(ngModel)]="filterState.projectId">
        <option [value]="-1">All</option>
        <option *ngFor="let p of allProjects" [value]="p.id">{{p.name}}</option>
    </select>
</div>

<div class="input-container">
    <label>Skill</label>
    <select required
        [(ngModel)]="filterState.skillId">
        <option [value]="-1">All</option>
        <option *ngFor="let s of allSkills" [value]="s.id">{{s.name}}</option>
    </select>
</div>

<div class="input-container">
    <label>Status</label>
    <select required
        [(ngModel)]="filterState.status">
        <option *ngFor="let s of statuses" [value]="s.id">{{s.name}}</option>
    </select>
</div>

<button md-raised-button class="search-button" color="primary" (click)="handleFilterChanged()">Search</button>
