// staffer-react-mobx/src/needs-panel/needs-table/NeedsTable.jsx
import './needs-table.scss';
import React from "react";
import {connect} from 'mobx-connect';
import {observer} from 'mobx-react';

@connect('store')
@observer
class NeedView extends React.Component {
    render() {
        let {need, onNeedSelected} = this.props;
        let {skillId, projectId, startDate, endDate, personId} = need;
        let {selectedNeed, entityMap: {skills, persons, projects}}= this.context.store;
        const selected = selectedNeed && need.id === selectedNeed.id;
        const skill = skills[skillId],
            project = projects[projectId],
            person = persons.get(personId);

        return (
            <tr className={`need-row pointer ${selected ? 'selected' : ''}`}
                onClick={()=>onNeedSelected(need)}>
                <td className="skill">{skill && skill.name}</td>
                <td className="project">{project && project.name}</td>
                <td>
                    <span className="start-date">{formatDate(startDate)}</span>
                    <br />
                    <span className="end-date">{formatDate(endDate)}</span>
                </td>
                <td className="assignment">{person && person.name}</td>
            </tr>

        );
    }

}

function formatDate(str) {
    let dt = new Date(str);
    return `${dt.getMonth() + 1}/${dt.getDate()}/${dt.getFullYear()}`;
}

@connect('store')
@observer
export default class NeedsTable extends React.Component {

    render() {
        const {needs} = this.props;
        const {store:{selectedNeed}} = this.context;

        return (
            <table className="mintable">
                <thead>
                <tr>
                    <th>Skill</th>
                    <th>Project</th>
                    <th>Date</th>
                    <th>Assignment</th>
                </tr>
                </thead>

                <tbody>
                {
                    needs.map(need=> {
                        return (
                            <NeedView need={need}
                                      key={need.id}
                                      onNeedSelected={()=>this.selectNeed(need)}/>
                        );
                    })
                }
                </tbody>
            </table>
        );
    }

    selectNeed(need) {
        let {store} = this.context;
        store.selectNeed(need);
    }

}

NeedsTable.defaultProps = {
    needs: []
};

// staffer-ng2-ngrxstore/src/app/needs-panel/needs-table/needs-table.component.ts
import {
    Component, EventEmitter, Input, Output,
    ChangeDetectionStrategy
} from "@angular/core";
import { Need } from "../../shared/models/index";
import { EntityCache } from "../../shared/store/state";

@Component({
    moduleId: module.id,
    selector: 'app-needs-table',
    templateUrl: 'needs-table.component.html',
    styleUrls: [ 'needs-table.component.css' ],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NeedsTableComponent {

    @Input() needs:Need[];
    @Input() cache:EntityCache;
    @Output() needSelected = new EventEmitter();

    selectedNeed = null;

    onNeedClick(need) {
        this.selectedNeed = need;
        this.needSelected.emit(this.selectedNeed);
    }

    getProjectName(projectId) {
        return this.cache && this.cache.projects[ projectId ].name;
    }

    getSkillName(skillId) {
        return this.cache && this.cache.skills[ skillId ].name;
    }

    getPersonName(personId) {
        return personId ? this.cache.people[ personId ].name : null;
    }
}

<table class="mintable needs-table">
    <tr>
        <th>Skill</th>
        <th>Project</th>
        <th>Date</th>
        <th>Assignment</th>
    </tr>
    <tr class="need-row pointer" *ngFor="let need of needs"
        (click)="onNeedClick(need)"
        [ngClass]="{ selected: (selectedNeed === need) }">
        <td class="skill">{{getSkillName(need.skillId)}}</td>
        <td class="project">{{getProjectName(need.projectId)}}</td>
        <td>
            <span
                class="start-date">{{need.startDate | date:'shortDate'}}</span><br>
            <span class="end-date">{{need.endDate | date:'shortDate'}}</span>
        </td>
        <td class="assignment">{{getPersonName(need.personId)}}</td>
    </tr>
</table>
